apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: influxdb
    name: {{ .Values.spec.destination.name }}
  project: default
  sources:
  - repoURL:  https://helm.influxdata.com/
    chart: influxdata/influxdb2
    targetRevision: 2.1.2
    helm:
      values: |
        persistence:
          enabled: true
          storageClassName: longhorn
          size: 2Gi
        adminUser:
          existingSecret: influxdb-auth
        ingress:
          enabled: true
          hostname: influxdb.raspberrypi.local
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
