---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: influxdb
spec:
  encryptedData:
    admin-password: AgAb70Id+dV5zzQWwvAmttw2k2KP236cHyU8I/INnH3prJB549OV8SxIC4jPy8oqioipDLoXoZ1qe1WW3/6W/X9FhSD683TlRcbLLgaKLpaP1zyDy5K7z953wQGguu0fVcKG/GFx9jpllDPyxrvacJKWwdbAfpQRPPBM8YdrgNLTRoHdV5EO7CfZWVU2XeZnN3ar/LdzQOxGjmemGT61JARxBoRoWpAlMTa+QnvClnUKDjTenPKFngj5oolMGh/QVHYtrKVexml6RR2v0UPQoeZWWL9tZRSBQeRJkf6+VGcUrwYlt9ouqKHKO22OG/LafBvKbZiWpERs9J3XZ12kdpt0Odk/KKOJcjTPGokaOEicOTbk4jfTbjDa8Y5YlJSVLw+QyrZjfmTSNyxM9Xi6IFFpR5/otkh/CkHNd6CD17lGmFeH88mKNC8drWXLhVd/FMM2XDJ5LVrq1kqeuegS7JzJNM3BTVOZg1rW9NN+rQM60LDYqJVrLPIzE4YwQBYA6ZWI8npgg5IkcWREnUH09yreGU8DtvwTuo8dS29I3W0a+DfKpMFNkf1aIH5QEPveocyv7ZAugnj2xaZM7ZhQPa4txi7VrXbs1+VXMZLFwnOd21EUJokDhC+ZpgImz9ppmc116rGKuBrTFxdLs8IEXErK9v3QpDmJFWHcrVlMCLHE9pN8cD7YEgNKIPHw1Onrsj7FO1JWeAvmrnj2wrz4
    admin-token: AgB4qN9GC00Rt1WDTUM+x+37+dv5PRdEiVPc8foKEqihOZ+7CMEcKsjR8NGjXBNYHJjKlLBomW9QJymQ46UD4HX22t3/Ek8KiBOCemaP+45QCWewP7CN695pspe6oDC//btGbVDkzk0LYUdmUwQx+4Ac3HuOcMapxZRuCn8vnZNM4bsVLBdSONpHaKH8+PeT0sq9x4H9wbKsSbqQN3HL2GmCUPLyXUE2i81K2CI2kiO4f56t0D9geVi0aotC6eTwwzOg0v21BFjT0UqkTU92vEOST0IckbWDoGd8qq3jy93zo1i1miZdvjNWBxmKY7io64RJOWNJmiE1jbkZFD1r8geBbitaz9xoKyTqTVl32IqEWe5NfNdWRsFANpqmtxQQrC5+swh6GlytemeKuXKIsz6WgY4MREZMwxV30bPIDDRdYFJvIRr4eukPkcxEbHRTKBI9nPtV3/i6qVbGUgZVaY3aNXx4uLpBK2Uah9zb6TjvuKPKj6g2FWA29dUgG+RWm1SB07UsfAXokDvUSBiXxI2wkCJmQ+1YiZGiy4F7TVKlCL/CJCznYZSpxosWYWtoK/zlNrYlKP2HCYD/JQu0fbbuz2TAdtPUSKc3nAUb7iolcAWnGA+usx6qCNqNlyYwEVfh2zZahWvinp52eJpLxm+vDo8raYKi7rrp8+ROc6ITFZAvTi/UuunvWbL1+T8G+k2d7DHSuhEb2Ybo/CVa8fi54YAxc3MLnxNN
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: influxdb
    type: Opaque
