repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: portainer
    url: https://portainer.github.io/k8s/
  - name: longhorn
    url: https://charts.longhorn.io
  - name: luke-codewalker
    url: https://luke-codewalker.github.io/helm-charts

releases:
  - name: longhorn
    chart: longhorn/longhorn
    atomic: true
    cleanupOnFail: true
    namespace: longhorn-system
    createNamespace: true
    values:
      - "./values/longhorn.yaml"

  - name: longhorn-ingress
    namespace: longhorn-system
    needs:
      - longhorn-system/longhorn
    chart: "./longhorn-manifests"

  - name: grafana
    needs:
      - longhorn-system/longhorn
    chart: grafana/grafana
    atomic: true
    cleanupOnFail: true
    namespace: grafana
    createNamespace: true
    values:
      - "./values/grafana.yaml"

  - name: portainer
    needs:
      - longhorn-system/longhorn
    chart: portainer/portainer
    atomic: true
    cleanupOnFail: true
    namespace: portainer
    createNamespace: true
    set:
      - name: ingress.hosts[0].host
        value: portainer.raspberrypi.local
      - name: ingress.hosts[0].paths[0].path
        value: /
    values:
      - "./values/portainer.yaml"

  - name: pi-home
    chart: luke-codewalker/pi-home
    namespace: pi-home
    createNamespace: true
    set:
      - name: host
        value: raspberrypi.local

  - name: progress-tracker
    chart: luke-codewalker/progress-tracker
    namespace: progress-tracker
    createNamespace: true
    set:
      - name: host
        value: raspberrypi.local
