repositories:
  - name: portainer
    url: https://portainer.github.io/k8s/
  - name: longhorn
    url: https://charts.longhorn.io
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: longhorn
    chart: longhorn/longhorn
    atomic: true
    cleanupOnFail: true
    namespace: longhorn-system
    createNamespace: true
    values:
      - "./values/longhorn.yaml"

  - name: argo
    atomic: true
    cleanupOnFail: true
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    values:
      - "./values/argo.yaml"

  - name: longhorn-ingress
    namespace: longhorn-system
    needs:
      - longhorn-system/longhorn
    chart: "./longhorn-manifests"

  - name: portainer
    needs:
      - longhorn-system/longhorn
    chart: portainer/portainer
    atomic: true
    cleanupOnFail: true
    namespace: portainer
    createNamespace: true
    set:
      - name: ingress.hosts[0].host
        value: portainer.raspberrypi.local
      - name: ingress.hosts[0].paths[0].path
        value: /
    values:
      - "./values/portainer.yaml"
