apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    name: {{ .Values.spec.destination.name }}
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.3
    helm:
      values: |
        ingress:
            enabled: true
            hosts: ["grafana.raspberrypi.local"]
            ingressClassName: "traefik"
        persistence:
            enabled: true
            type: pvc
            storageClassName: longhorn
            size: 2Gi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
