apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: postgres
    name: {{ .Values.spec.destination.name }}
  project: default
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 16.1.0
    helm:
      values: |
        global:
          defaultStorageClass: longhorn
        primary:
          persistence:
            size: 2.5Gi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true