apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    name: {{ .Values.spec.destination.name }}
  project: default
  sources:
  - repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 16.1.0
    helm:
      values: |
        ingress:
            enabled: true
            hosts: ["grafana.raspberrypi.local"]
            ingressClassName: "traefik"
        persistence:
            enabled: true
            type: pvc
            storageClassName: longhorn
            size: 5Gi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true