apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: progress-tracker
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: progress-tracker
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    chart: progress-tracker
    repoURL: https://luke-codewalker.github.io/helm-charts/
    targetRevision: HEAD
    helm:
      values: |
        host: raspberrypi.local
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
