apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: progress-tracker
  namespace: {{ .Values.spec.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.namespace }}
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    chart: progress-tracker
    repoURL: https://luke-codewalker.github.io/helm-charts/
    targetRevision: 0.1.1
    helm:
      values: |
        host: raspberrypi.local
  syncPolicy:
    automated: {}
