apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psql-app-test
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: psql-app-test
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    chart: psql-app-test
    repoURL: https://luke-codewalker.github.io/helm-charts/
    targetRevision: 0.4.6
    helm:
      values: |
        host: raspberrypi.local
        port: 2024
        image:
          tag: 1.1.1

  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
