---
- name: Modify PoE Fan Speeds Configuration for Pi 4
  hosts: pi4
  become: yes

  tasks:
    - name: Append PoE Fan Speed Configurations to /boot/firmware/config.txt
      lineinfile:
        path: /boot/firmware/config.txt
        line: "{{ item }}"
      loop:
        - "dtparam=poe_fan_temp0=60000"
        - "dtparam=poe_fan_temp1=65000"
        - "dtparam=poe_fan_temp2=72000"
        - "dtparam=poe_fan_temp3=80000"

    - name: Reboot Pi 4 to Apply Changes
      include_tasks: reboot.yaml
