---
- name: Turn of BT and Wifi to save power on all devices
  hosts: pi4
  become: yes

  tasks:
    - name: Append configurations to /boot/config.txt
      lineinfile:
        path: /boot/firmware/config.txt
        line: "{{ item }}"
      loop:
        - "dtoverlay=disable-wifi"
        - "dtoverlay=disable-bt"

    - name: Reboot to apply Changes
      include_tasks: reboot.yaml
